name: Commands
version: '1.0-SNAPSHOT'
main: org.example.commands.commands.Commands
api-version: '1.20'
commands:
  die:
    description: An easy way to kill
    usage: /<command>
  god:
    description: Become invisible
    usage: /<command>
    aliases:
      -kodymode
      -pro
  feed:
    description: Feed yourself without eating
    usage: /<command>
  Test:
    description: Test
    permission:  permissions.test
    permission-message: You don't have permission to use this
    usage: /<command>