name: Commands
version: '1.0-SNAPSHOT'
main: org.example.commands.commands.Commands
api-version: '1.20'
commands:
  die:
    description: An easy way to kill
    usage: /<command>
  god:
    description: Become invisible
    usage: /<command>
    aliases:
      -kodymode
      -pro
  feed:
    description: Feed yourself without eating
    usage: /<command>