name: ArmorStandGUI
version: '${project.version}'
main: org.example.armorstandsgui.armorstandgui.ArmorStandGUI
api-version: '1.20'
commands:
  armor-stands:
    description: 'Create a armor stand'
    usage: /<command>
    aliases:
      -as
