name: ArmorStandGUI
version: '${project.version}'
main: org.example.armorstandsgui.armorstandgui.ArmorStandGUI
api-version: '1.20'
commands:
  armor-stand:
    description: Opens the armor stand menu
    usage: /armor-stand
    aliases:
      -as
